image: openjdk:11

stages:
  - build
  - test
  - docker
  - deploy

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
test:
  stage: test
  script:
    - ./gradlew test
    - ./gradlew jacocoTestCoverageVerification
  artifacts:
    paths:
      - build/reports
production:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
      #App name from prev step  Key from your heroku account
    - dpl --provider=heroku --app=simple-autos-data-candc --api-key=$Heroku_simple_autos_key
  only: # Heroku will ONLY deploy from main or master branch!
    - master
docker:
  image: docker:20
  needs:
    - build
    - test
  stage: docker
  services:
    - docker:dind
  before_script:
    - echo $CI_BUILD_TOKEN | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE":"$CI_PIPELINE_IID" .
    - docker push "$CI_REGISTRY_IMAGE":"$CI_PIPELINE_IID"
